---
version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'composer'
    directory: '/'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'npm'
    directory: '/tests/prettier'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'docker'
    directory: '/tests/prettier'
    schedule:
      interval: 'daily'
