---
reports:
  github-security:
    extra:
      total: Total
    colors:
      LOW: '#808080'
      MODERATE: '#FFFF00'
      HIGH: '#FFC100'
      CRITICAL: '#FF0000'
    storage:
      github-discussion:
        url: https://github.com/PedroTroller/K-pi/discussions/8
  coverage:
    storage:
      github-discussion:
        url: https://github.com/PedroTroller/K-pi/discussions/12
    check-reporter:
      github-status:
        states: higher-is-better
        unit: '%'
  outdated-dependencies:
    storage:
      github-discussion:
        url: https://github.com/PedroTroller/K-pi/discussions/14
    check-reporter:
      github-status:
        states: lower-is-better
        unit:
          singular: ' dependency'
          plural: ' dependencies'
  class-bugs:
    storage:
      github-discussion:
        url: https://github.com/PedroTroller/K-pi/discussions/22
    check-reporter:
      github-status:
        states:
          on-lower: success
          on-higher: success
        unit:
          singular: ' bug'
          plural: ' bugs'
