---
overrides:
  - files:
      - '*.yaml'
      - '*.yml'
      - '*.neon'
      - '*.yaml.dist'
      - '*.yml.dist'
      - '*.neon.dist'
    options:
      parser: yaml
      tabWidth: 2
      singleQuote: true
  - files:
      - '*.json'
      - '*.json.dist'
    options:
      parser: json
      tabWidth: 4
  - files:
      - '*.php'
    options:
      parser: php
      printWidth: 80
      tabWidth: 4
      singleQuote: true
      phpVersion: '8.2'
      braceStyle: 'per-cs'
      trailingCommaPHP: false
  - files:
      - '*.md'
    options:
      parser: markdown
      printWidth: 80
      proseWrap: always
