---
on:
  push:
    branches:
      - main
  pull_request: ~
  schedule:
    - cron: '0 6 * * 1-5' # Mon to Fri at 8:00 (Paris GMT+2)

jobs:

  github-security:
    if: github.event_name == 'schedule' || github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        id: script
        with:
          script: |
            const query = `
              query($cursor: String, $owner: String!, $repo: String!) {
                repository(owner: $owner, name: $repo) {
                  vulnerabilityAlerts(states: OPEN, first: 100, after: $cursor) {
                    pageInfo {
                      endCursor
                    }
                    nodes {
                      securityVulnerability {
                        severity
                      }
                    }
                  }
                }
              }
            `;

            let cursor            = null;
            const countBySeverity = {CRITICAL: 0, HIGH: 0, MODERATE: 0, LOW: 0};

            do {
                const variables = { cursor: cursor, owner: context.repo.owner, repo: context.repo.repo };
                const result    = await github.graphql(query, variables);

                for(const alert of result.repository.vulnerabilityAlerts.nodes) {
                    if (!countBySeverity[alert.securityVulnerability.severity]) {
                        countBySeverity[alert.securityVulnerability.severity] = 0;
                    }

                    countBySeverity[alert.securityVulnerability.severity]++;
                }

                cursor = result.repository.vulnerabilityAlerts.pageInfo.endCursor;
            } while(null !== cursor)

            console.log(countBySeverity);

            return countBySeverity;
      - uses: actions/checkout@v4
      - uses: ./
        with:
          report: github-security
          command: compile
          values: ${{ steps.script.outputs.result }}

  outdated-dependencies:
    if: github.event_name == 'schedule' || github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: latest
          tools: phpmetrics/phpmetrics
      - name: Compile
        id: phpmetrics
        run: |
          phpmetrics src --report-json=phpmetrics/report.json
          echo "composer.json=$(cat phpmetrics/report.json | jq --raw-output '.composer.packages|map(select(.status=="outdated"))|length')" > $GITHUB_OUTPUT
      - uses: ./
        with:
          report: outdated-dependencies
          command: compile
          values: ${{ toJson(steps.phpmetrics.outputs) }}

  phpspec:
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: tests/compose.yaml
    permissions:
      statuses: write
    steps:
      - uses: actions/checkout@v4
      - run: docker compose run --rm --build --entrypoint=vendor/bin/phpspec php --config=phpspec.yaml.dist run --no-interaction
      - name: XPath
        id: xpath
        run: |
          sudo apt-get install -y libxml-xpath-perl

          PERCENT=$(cat coverage/phpspec/index.xml | xpath -q -e '/phpunit/project/directory[@name="/"]/totals/lines/@percent' | cut -f 2 -d "=" | tr -d \")

          echo "phpspec=${PERCENT}" > $GITHUB_OUTPUT
      - uses: ./
        with:
          report: coverage
          command: ${{ github.event_name == 'pull_request' && 'check' || 'compile' }}
          values: ${{ toJson(steps.xpath.outputs) }}
