---
on:
  push:
    branches:
      - main
  pull_request: ~
  schedule:
    - cron: '0 6 * * 1-5' # Mon to Fri at 8:00 (Paris GMT+2)

jobs:

  phpspec:
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: tests/compose.yaml
    permissions:
      statuses: write
    steps:
      - uses: actions/checkout@v4
      - run: docker compose run --rm --build --entrypoint=vendor/bin/phpspec php --config=phpspec.yaml.dist run --no-interaction
      - name: XPath
        id: xpath
        run: |
          sudo apt-get install -y libxml-xpath-perl

          PERCENT=$(cat coverage/phpspec/index.xml | xpath -q -e '/phpunit/project/directory[@name="/"]/totals/lines/@percent' | cut -f 2 -d "=" | tr -d \")

          echo "phpspec=${PERCENT}" > $GITHUB_OUTPUT
      - uses: ./
        with:
          report: coverage
          command: ${{ github.event_name == 'pull_request' && 'check' || 'compile' }}
          values: ${{ toJson(steps.xpath.outputs) }}
