---
on: push

permissions:
  checks: write
  statuses: write

jobs:
  github-security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        id: script
        with:
          script: |
            const query = `
              query($cursor: String, $owner: String!, $repo: String!) {
                repository(owner: $owner, name: $repo) {
                  vulnerabilityAlerts(states: OPEN, first: 100, after: $cursor) {
                    pageInfo {
                      endCursor
                    }
                    nodes {
                      securityVulnerability {
                        severity
                      }
                    }
                  }
                }
              }
            `;

            let cursor            = null;
            const countBySeverity = {CRITICAL: 0, HIGH: 0, MODERATE: 0, LOW: 0};

            do {
                const variables = { cursor: cursor, owner: context.repo.owner, repo: context.repo.repo };
                const result    = await github.graphql(query, variables);

                for(const alert of result.repository.vulnerabilityAlerts.nodes) {
                    if (!countBySeverity[alert.securityVulnerability.severity]) {
                        countBySeverity[alert.securityVulnerability.severity] = 0;
                    }

                    countBySeverity[alert.securityVulnerability.severity]++;
                }

                cursor = result.repository.vulnerabilityAlerts.pageInfo.endCursor;
            } while(null !== cursor)

            console.log(countBySeverity);

            return countBySeverity;
      - uses: actions/checkout@v4
      - uses: ./
        with:
          report: github-security
          command: compile
          values: ${{ steps.script.outputs.result }}
  phpstan-baseline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          report: phpstan-baseline
          command: check
          values: '{"php/baseline/phpstan/deprecation.neon": 123, "test": 12}'
